const skills = [
  {
    id: 1,
    name: 'html',
    type: 'language',
    title: 'HTML5',
    sectionTitle: 'Языки',
  },
  {
    id: 2,
    name: 'css',
    type: 'language',
    title: 'CSS3',
    sectionTitle: 'Языки',
  },
  {
    id: 3,
    name: 'scss',
    type: 'preprocessor',
    title: 'SASS (SCSS)',
    sectionTitle: 'Препроцессоры и Шаблонизаторы',
  },
  {
    id: 4,
    name: 'javascript',
    type: 'language',
    title: 'JavaScript',
    sectionTitle: 'Языки',
  },
  {
    id: 5,
    name: 'react',
    type: 'library',
    title: 'React',
    sectionTitle: 'Библиотеки и Фреймворки',
  },
  {
    id: 6,
    name: 'webpack',
    type: 'tools',
    title: 'Webpack',
    sectionTitle: 'Инструменты',
  },
  {
    id: 7,
    name: 'wordpress',
    type: 'cms',
    title: 'WordPress',
    sectionTitle: 'Системы управления содержимым',
  },
  {
    id: 8,
    name: 'git',
    type: 'tools',
    title: 'git',
    sectionTitle: 'Инструменты',
  },
  {
    id: 9,
    name: 'figma',
    type: 'tools',
    title: 'Figma',
    sectionTitle: 'Инструменты',
  },
  {
    id: 12,
    name: 'vue',
    type: 'library',
    title: 'Vue',
    sectionTitle: 'Библиотеки и Фреймворки',
  },
  {
    id: 13,
    name: 'prettier',
    type: 'tools',
    title: 'Prettier',
    sectionTitle: 'Инструменты',
  },
  {
    id: 14,
    name: 'eslint',
    type: 'tools',
    title: 'Eslint',
    sectionTitle: 'Инструменты',
  },
  {
    id: 15,
    name: 'nuxt',
    type: 'library',
    title: 'Nuxt',
    sectionTitle: 'Библиотеки и Фреймворки',
  },
  {
    id: 16,
    name: 'stylus',
    type: 'preprocessor',
    title: 'Stylus',
    sectionTitle: 'Препроцессоры и Шаблонизаторы',
  },
  {
    id: 17,
    name: 'twig',
    type: 'preprocessor',
    title: 'Twig',
    sectionTitle: 'Препроцессоры и Шаблонизаторы',
  },
  {
    id: 18,
    name: 'jquery',
    type: 'library',
    title: 'jQuery',
    sectionTitle: 'Библиотеки и Фреймворки',
  },
];

export default skills;
